"""add_notifications_and_membership_status

Revision ID: 0e2512635461
Revises: 410e5de35b77
Create Date: 2026-03-31 14:14:30.412224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2512635461'
down_revision: Union[str, None] = '410e5de35b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    membershipstatus = sa.Enum('pending', 'accepted', 'rejected', name='membershipstatus')
    membershipstatus.create(op.get_bind(), checkfirst=True)
    
    # Add column as nullable first
    op.add_column('memberships', sa.Column('status', membershipstatus, nullable=True))
    
    # Set default value for existing rows (all existing memberships are accepted)
    op.execute("UPDATE memberships SET status = 'accepted' WHERE status IS NULL")
    
    # Make column non-nullable
    op.alter_column('memberships', 'status', nullable=False)
    
    # Create notifications table
    op.create_table('notifications',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('type', sa.Enum('group_invitation', name='notificationtype'), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('group_id', sa.UUID(), nullable=True),
        sa.Column('membership_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
        sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_column('memberships', 'status')
    sa.Enum(name='membershipstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='notificationtype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
